[build]
target = "xtensa-esp32s3-none-elf.json"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor --log-format defmt"
rustflags = [
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"
EMBASSY_EXECUTOR_TASK_ARENA_SIZE = "65536"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
