#![no_std]
#![no_main]

mod bq76920_task;
mod data_types;
mod global_state;
mod led_status_task;
mod sc8815_task;
mod shared;
mod i2c1_slave;
mod scheduler;
mod sleep_manager;

use bq769x0_async_rs::{BatteryConfig, Bq769x0, Enabled as BqCrcEnabled, ProtectionConfig};
use defmt::{info, warn, debug};
use embassy_embedded_hal::shared_bus::asynch::i2c::I2cDevice;
use embassy_executor::Spawner;
use embassy_stm32::{
    bind_interrupts,
    gpio::{Level, Output, OutputOpenDrain, Speed},
    i2c::{self, Config as I2cConfig, I2c, SlaveAddrConfig},
    peripherals::{I2C2, I2C1},
    time::Hertz,
};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use embassy_time::{Duration, Timer};
use static_cell::StaticCell;
use embassy_stm32::interrupt::typelevel::Interrupt as _;

// Fixed I2C address for BQ7692003PWR (7‑bit).
// Per TI device comparison table: the "03" variant uses CRC and a fixed
// I2C address 0x08. Other orderable numbers (e.g. BQ7692006) use 0x18.
const BQ76920_I2C_ADDR: u8 = 0x08;
use {defmt_rtt as _, panic_probe as _};

// Build-id style静态标记（不影响功能，仅用于离线验证产物是否包含本文件的最新改动）
#[used]
static _BUILD_MARK_MAIN: &str = "SB.MAIN.BUILD-MARK/2025-09-22";

bind_interrupts!(struct I2c2Irqs {
    I2C2 => i2c::EventInterruptHandler<I2C2>, i2c::ErrorInterruptHandler<I2C2>;
});

// Bind I2C1 interrupts so the slave listen/respond paths can wake properly.
bind_interrupts!(struct I2c1Irqs {
    I2C1 => i2c::EventInterruptHandler<I2C1>, i2c::ErrorInterruptHandler<I2C1>;
});

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    let mut config = embassy_stm32::Config::default();
    config.rcc.ls = embassy_stm32::rcc::LsConfig::default_lse();
    let p = embassy_stm32::init(config);

    // Ensure I2C1 clock remains available during SLEEP: APB1SMENR.I2C1SMEN must be 1.
    // Read-modify-write defensively and print the state for acceptance logging.
    {
        let rcc = embassy_stm32::pac::RCC;
        let apb1smenr = rcc.apb1smenr().read().0;
        // Per RM0377, APB1SMENR bit 21 is I2C1SMEN.
        const I2C1SMEN_BIT: u32 = 1 << 21;
        let i2c1smen_on = (apb1smenr & I2C1SMEN_BIT) != 0;
        debug!("apb1smenr=0x{:08x} i2c1smen={}", apb1smenr, i2c1smen_on);
        if !i2c1smen_on {
            warn!("I2C1SMEN=0: enable I2C1 clock in Sleep mode via RCC_APB1SMENR before relying on SLEEP wake");
        }
    }

    // Configure external I2C1 slave (PB6/PB7 @0x35) using embassy API only.
    // Ensure NVIC line is unmasked so I2C interrupts can wake from SLEEP.
    unsafe {
        #[allow(non_snake_case)]
        {
            // Type-level NVIC handle is generated by embassy for this MCU.
            embassy_stm32::interrupt::typelevel::I2C1::unpend();
            embassy_stm32::interrupt::typelevel::I2C1::enable();
        }
    }
    let mut i2c1_cfg = I2cConfig::default();
    i2c1_cfg.frequency = Hertz(100_000);
    let i2c1_blocking = I2c::new_blocking(p.I2C1, p.PB6, p.PB7, i2c1_cfg);
    let i2c1_dev = i2c1_blocking.into_slave_multimaster(SlaveAddrConfig::basic(0x35));

    // Keep SC8815 power stage disabled during configuration.
    let ce = Output::new(p.PA10, Level::High, Speed::Low);
    let pstop = Output::new(p.PA9, Level::High, Speed::Low);
    let mut exit_shipmode = Output::new(p.PA1, Level::Low, Speed::Low);
    debug!("boot CE=H PSTOP=H ts {}", env!("SB_BUILD_TS"));

    // Post-startup diagnostics: compact readback
    debug!("i2c1:readback");
    {
        let regs = embassy_stm32::pac::I2C1;
        let cr1 = regs.cr1().read().0;
        let oar1 = regs.oar1().read().0;
        let isr = regs.isr().read().0;
        let timing = regs.timingr().read().0;
        debug!("i2c1 cr1=0x{:x} oar1=0x{:x} tm=0x{:x} isr=0x{:x}", cr1, oar1, timing, isr);
        debug!("i2c1-nvic:on");
    }

    // Prepare INNER I2C bus (I2C2 on PB10/PB11) with 100 kHz clock and wrap as shared bus.
    let mut i2c_config = I2cConfig::default();
    i2c_config.frequency = Hertz(100_000);
    let i2c = I2c::new(
        p.I2C2,
        p.PB10,
        p.PB11,
        I2c2Irqs,
        p.DMA1_CH4,
        p.DMA1_CH5,
        i2c_config,
    );
    type I2c2Bus = Mutex<CriticalSectionRawMutex, I2c<'static, embassy_stm32::mode::Async, i2c::mode::Master>>;
    static I2C2_BUS: StaticCell<I2c2Bus> = StaticCell::new();
    let i2c_bus: &'static I2c2Bus = I2C2_BUS.init(Mutex::new(i2c));

    // Initialize pubsub channels and get publishers for BQ76920 task
    let (
        _measurements_pub,
        _measurements_chan,
        sc8815_alerts_pub,
        _sc8815_alerts_chan,
        bq76920_alerts_pub,
        _bq76920_alerts_chan,
        sc8815_meas_pub,
        sc8815_meas_chan,
        bq76920_meas_pub,
        bq76920_meas_chan,
        balancing_cv_pub,
        balancing_cv_chan,
        global_state_pub,
        global_state_chan,
    ) = shared::init_pubsubs();

    // Gate other tasks on successful BQ76920 initialization using fixed I2C address.
    let mut ship_mode_pulsed = false;
    let _selected_bq_addr = loop {
        debug!("bq:init try 0x{:02x}", BQ76920_I2C_ADDR);
        let i2c_dev_for_bq = I2cDevice::new(i2c_bus);
        let mut bq: Bq769x0<_, BqCrcEnabled, 5> =
            Bq769x0::new(i2c_dev_for_bq, BQ76920_I2C_ADDR, 3, None);
        let cfg = BatteryConfig {
            overvoltage_trip: 3650,  // 3.65V per cell
            undervoltage_trip: 2500, // 2.50V per cell
            protection_config: ProtectionConfig {
                scd_limit: 15_000, // 15A short-circuit
                ocd_limit: 10_000, // 10A overcurrent
                ..BatteryConfig::default().protection_config
            },
            rsense: 3, // 3 mΩ sense resistor
            ..Default::default()
        };

        match bq.try_apply_config(&cfg).await {
            Ok(_) => {
                debug!("bq:init ok 0x{:02x}", BQ76920_I2C_ADDR);
                // Spawn the continuous BQ76920 task now that init succeeded.
                let i2c_dev_runtime = I2cDevice::new(i2c_bus);
                let sc8815_alerts_sub = _sc8815_alerts_chan
                    .subscriber()
                    .expect("Allocate SC8815 alerts subscriber for BQ task");
    _spawner
        .spawn(bq76920_task::bq76920_task(
            i2c_dev_runtime,
            BQ76920_I2C_ADDR,
            3,    // sense resistor mΩ
            None, // no NTC parameters provided
            bq76920_alerts_pub,
            bq76920_meas_pub,
            sc8815_alerts_sub,
            balancing_cv_pub,
        ).expect("bq token"));
                // Late I2C1 diag once BQ is alive, to avoid early-RTT drop
                {
                    let regs = embassy_stm32::pac::I2C1;
                    let cr1 = regs.cr1().read().0;
                    let oar1 = regs.oar1().read().0;
                    let isr = regs.isr().read().0;
                    let timing = regs.timingr().read().0;
                debug!("i2c1(late) c=0x{:x} o=0x{:x} t=0x{:x} s=0x{:x}", cr1, oar1, timing, isr);
                }

                break BQ76920_I2C_ADDR;
            }
            Err(e) => {
                warn!("bq:init fail 0x{:02x} {:?}", BQ76920_I2C_ADDR, e);
            }
        }
        if !ship_mode_pulsed {
            debug!("ship-pulse");
            exit_shipmode.set_high();
            Timer::after(Duration::from_millis(500)).await;
            exit_shipmode.set_low();
            ship_mode_pulsed = true;
            continue;
        }

        warn!("bq:noresp retry");
        Timer::after(Duration::from_secs(1)).await;
    };

    // Create a subscriber for BQ76920 measurements to feed charger control logic.
    let bq76920_meas_sub = bq76920_meas_chan
        .subscriber()
        .expect("Allocate BQ76920 measurements subscriber");

    // Spawn SC8815 charger management task now that the protection IC is live.
    let i2c_dev_for_sc = I2cDevice::new(i2c_bus);
    let balancing_cv_sub = balancing_cv_chan
        .subscriber()
        .expect("Allocate BalancingCv subscriber for charger task");
    _spawner
        .spawn(sc8815_task::sc8815_task(
            ce,
            pstop,
            exit_shipmode,
            i2c_dev_for_sc,
            sc8815_task::SC8815_DEFAULT_ADDRESS,
            sc8815_alerts_pub,
            sc8815_meas_pub,
            bq76920_meas_sub,
            balancing_cv_sub,
        ).expect("sc token"));

    // 启动 Global State 聚合任务
    let gs_sc_alerts_sub = _sc8815_alerts_chan
        .subscriber()
        .expect("Allocate SC8815 alerts subscriber for GS task");
    let gs_sc_meas_sub = sc8815_meas_chan
        .subscriber()
        .expect("Allocate SC8815 measurements subscriber for GS task");
    let gs_bq_alerts_sub = _bq76920_alerts_chan
        .subscriber()
        .expect("Allocate BQ76920 alerts subscriber for GS task");
    let gs_bal_cv_sub = balancing_cv_chan
        .subscriber()
        .expect("Allocate BalancingCv subscriber for GS task");
    _spawner
        .spawn(global_state::global_state_task(
            gs_sc_alerts_sub,
            gs_sc_meas_sub,
            gs_bq_alerts_sub,
            gs_bal_cv_sub,
            global_state_pub,
        ).expect("gs token"));

    // 启动 LED 状态任务
    let led_pin = OutputOpenDrain::new(p.PA5, Level::High, Speed::Low);
    let led_global_state_sub = global_state_chan
        .subscriber()
        .expect("Allocate GlobalState subscriber for LED task");
    _spawner
        .spawn(led_status_task::led_status_task(
            led_pin,
            led_global_state_sub,
        ).expect("led token"));

    // Spawn sleep manager + power scheduler (driven by GlobalState)
    _spawner
        .spawn(sleep_manager::sleep_task().expect("sleep-mgr token"));

    let gs_sub_for_sched = global_state_chan
        .subscriber()
        .expect("Allocate GS subscriber for scheduler");
    _spawner
        .spawn(scheduler::power_scheduler_task(gs_sub_for_sched).expect("sched token"));

    // (Optional) EXTI for BQ ALERT can be enabled here if needed for additional wake sources.

    // Spawn I2C1 slave + snapshot mirror tasks for the external interface
    debug!("i2c1:spawn");
    _spawner.spawn(i2c1_slave::slave_task(i2c1_dev).expect("slave token"));
    _spawner
        .spawn(i2c1_slave::sc_meas_mirror_task(sc8815_meas_chan).expect("sc-mirror token"));
    _spawner
        .spawn(i2c1_slave::bq_meas_mirror_task(bq76920_meas_chan).expect("bq-mirror token"));

    // Main loop: subscribe global-state and log immediate changes.
    let mut gs_sub_for_log = global_state_chan
        .subscriber()
        .expect("Allocate GlobalState subscriber for main logger");
    let mut last_seen: Option<crate::global_state::BatteryGlobalState> = None;
    let mut last_snap = embassy_time::Instant::now();
    loop {
        // When AC is absent, block waiting for actual state changes (no periodic timers)
        let ac = last_seen.map(|v| v.ac_present).unwrap_or(false);
        if !ac {
            let s = gs_sub_for_log.next_message_pure().await;
            if last_seen.map(|v| v != s).unwrap_or(true) {
                let mut b: u8 = 0;
                if s.ac_present { b |= 1<<0; }
                if s.charging { b |= 1<<1; }
                if s.charging_paused { b |= 1<<2; }
                if s.preparing { b |= 1<<3; }
                if s.full { b |= 1<<4; }
                if s.balancing_active { b |= 1<<5; }
                if s.fault_battery { b |= 1<<6; }
                if s.fault_charger { b |= 1<<7; }
                warn!("st b=0x{:02x}", b);
                last_seen = Some(s);
            }
            continue;
        }

        // AC present: retain lightweight 10ms polling and 1s snapshot
        if let Some(s) = gs_sub_for_log.try_next_message_pure() {
            if last_seen.map(|v| v != s).unwrap_or(true) {
                let mut b: u8 = 0;
                if s.ac_present { b |= 1<<0; }
                if s.charging { b |= 1<<1; }
                if s.charging_paused { b |= 1<<2; }
                if s.preparing { b |= 1<<3; }
                if s.full { b |= 1<<4; }
                if s.balancing_active { b |= 1<<5; }
                if s.fault_battery { b |= 1<<6; }
                if s.fault_charger { b |= 1<<7; }
                warn!("st b=0x{:02x}", b);
                last_seen = Some(s);
            }
        }
        let now = embassy_time::Instant::now();
        if now.duration_since(last_snap) >= Duration::from_secs(1) {
            if let Some(s) = last_seen {
                debug!("snap ac={} chg={} p={} pr={} f={} bal={} bf={} cf={}",
                    s.ac_present, s.charging, s.charging_paused, s.preparing, s.full,
                    s.balancing_active, s.fault_battery, s.fault_charger);
            }
            last_snap = now;
        }
        Timer::after(Duration::from_millis(10)).await;
    }
}
