#![no_std]
#![no_main]

mod bq76920_task;
mod data_types;
// mod global_state; // removed to save flash; LEDs derive state locally
mod activity;
mod failsafe;
mod i2c1_slave;
mod leds4_task;
mod sc8815_task;
mod state_bits;
// scheduler removed (合并到 failsafe + SC 路径)
mod shared;
mod sleep_manager;

use bq769x0_async_rs::{BatteryConfig, Bq769x0, Enabled as BqCrcEnabled};
// no direct info! logs to减小尺寸
use embassy_embedded_hal::shared_bus::asynch::i2c::I2cDevice;
use embassy_executor::Spawner;
use embassy_stm32::interrupt::typelevel::Interrupt as _;
use embassy_stm32::{
    bind_interrupts,
    gpio::{Level, Output, Speed},
    i2c::{self, Config as I2cConfig, I2c, SlaveAddrConfig},
    peripherals::{I2C1, I2C2},
    time::Hertz,
};
use embassy_stm32::{exti::ExtiInput, gpio::Pull};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use embassy_time::{Duration, Instant, Timer};
use static_cell::StaticCell;

// Fixed I2C address for BQ7692003PWR (7‑bit).
// Per TI device comparison table: the "03" variant uses CRC and a fixed
// I2C address 0x08. Other orderable numbers (e.g. BQ7692006) use 0x18.
const BQ76920_I2C_ADDR: u8 = 0x08;
use {defmt_rtt as _, panic_probe as _};

// (no build-id marker to save flash)

bind_interrupts!(struct I2c2Irqs {
    I2C2 => i2c::EventInterruptHandler<I2C2>, i2c::ErrorInterruptHandler<I2C2>;
});

// Bind I2C1 interrupts so the slave listen/respond paths can wake properly.
bind_interrupts!(struct I2c1Irqs {
    I2C1 => i2c::EventInterruptHandler<I2C1>, i2c::ErrorInterruptHandler<I2C1>;
});

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    let mut config = embassy_stm32::Config::default();
    config.rcc.ls = embassy_stm32::rcc::LsConfig::default_lse();
    // Single firmware profile: keep debug disabled during sleep for lowest current.
    config.enable_debug_during_sleep = false;
    let p = embassy_stm32::init(config);

    // 使用默认线程模式执行器：WFE 进入轻度 SLEEP（非 STOP）。
    // 启动日志（必须打印，复用与 sleep_task 相同的格式字符串以节省 FLASH）。
    defmt::info!("sleep: start (mode=SLEEP)");

    // (Removed: APB1SMENR diagnostics to save flash)

    // Configure external I2C1 slave (PB6/PB7 @0x35) using embassy API only.
    // Ensure NVIC line is unmasked so I2C interrupts can wake from SLEEP.
    unsafe {
        #[allow(non_snake_case)]
        {
            // Type-level NVIC handle is generated by embassy for this MCU.
            embassy_stm32::interrupt::typelevel::I2C1::unpend();
            embassy_stm32::interrupt::typelevel::I2C1::enable();
        }
    }
    let mut i2c1_cfg = I2cConfig::default();
    i2c1_cfg.frequency = Hertz(100_000);
    let i2c1_blocking = I2c::new_blocking(p.I2C1, p.PB6, p.PB7, i2c1_cfg);
    let i2c1_dev = i2c1_blocking.into_slave_multimaster(SlaveAddrConfig::basic(0x35));
    // (Optional: I2C1.CR1.WUPEN for wake-from-STOP is omitted to save flash; RTC remains primary wake source.)

    // Keep SC8815 power stage disabled during configuration.
    let ce = Output::new(p.PA10, Level::High, Speed::Low);
    let pstop = Output::new(p.PA9, Level::High, Speed::Low);
    let mut exit_shipmode = Output::new(p.PA1, Level::Low, Speed::Low);
    // BQ76920 may power-up in SHIP; assert wake pin early to bring it to NORMAL.
    defmt::info!("bq:wake");
    exit_shipmode.set_high();
    Timer::after(Duration::from_millis(1200)).await;
    exit_shipmode.set_low();

    // (Removed: raw I2C1 PAC readbacks to save flash)

    // Prepare INNER I2C bus (I2C2 on PB10/PB11) with 100 kHz clock and wrap as shared bus.
    // Ensure I2C2 NVIC is unmasked to avoid async transactions stalling.
    unsafe {
        #[allow(non_snake_case)]
        {
            embassy_stm32::interrupt::typelevel::I2C2::unpend();
            embassy_stm32::interrupt::typelevel::I2C2::enable();
        }
    }
    let mut i2c_config = I2cConfig::default();
    i2c_config.frequency = Hertz(100_000);
    let i2c = I2c::new(
        p.I2C2, p.PB10, p.PB11, I2c2Irqs, p.DMA1_CH4, p.DMA1_CH5, i2c_config,
    );
    type I2c2Bus =
        Mutex<CriticalSectionRawMutex, I2c<'static, embassy_stm32::mode::Async, i2c::mode::Master>>;
    static I2C2_BUS: StaticCell<I2c2Bus> = StaticCell::new();
    let i2c_bus: &'static I2c2Bus = I2C2_BUS.init(Mutex::new(i2c));

    // Initialize pubsub channels and get publishers for BQ76920 task
    let (
        _measurements_pub,
        _measurements_chan,
        sc8815_alerts_pub,
        _sc8815_alerts_chan,
        bq76920_alerts_pub,
        _bq76920_alerts_chan,
        sc8815_meas_pub,
        sc8815_meas_chan,
        bq76920_meas_pub,
        bq76920_meas_chan,
        balancing_cv_pub,
        balancing_cv_chan,
    ) = shared::init_pubsubs();

    // 先尝试初始化 BQ76920（总重试 ≤ 500 ms）
    defmt::info!("fw:boot smart-battery");
    defmt::info!("bq:init");
    let probe_start = Instant::now();
    let probe_deadline = probe_start + Duration::from_millis(500);
    let tried_addresses = [BQ76920_I2C_ADDR, 0x18u8];
    let mut cfg_template = BatteryConfig::default();
    cfg_template.overvoltage_trip = 3650;
    cfg_template.undervoltage_trip = 2500;
    cfg_template.protection_config.scd_limit = 15_000;
    cfg_template.protection_config.ocd_limit = 10_000;
    cfg_template.rsense = 3;

    let mut bq_init_addr: Option<u8> = None;
    'addr_loop: for addr in tried_addresses.iter().copied() {
        if Instant::now() >= probe_deadline {
            break;
        }
        defmt::debug!("bq:try=0x{:02x}", addr);
        let i2c_dev_for_bq = I2cDevice::new(i2c_bus);
        let mut probe: Bq769x0<_, BqCrcEnabled, 5> = Bq769x0::new(i2c_dev_for_bq, addr, 3, None);
        if probe.try_apply_config(&cfg_template).await.is_ok() {
            defmt::info!("bq:0x{:02x}", addr);
            crate::failsafe::set_bq_online(true);
            bq_init_addr = Some(addr);
            break;
        }

        if Instant::now() >= probe_deadline {
            break;
        }
        exit_shipmode.set_high();
        Timer::after(Duration::from_millis(150)).await;
        exit_shipmode.set_low();
        if Instant::now() >= probe_deadline {
            break;
        }
        let i2c_dev_for_bq = I2cDevice::new(i2c_bus);
        let mut probe: Bq769x0<_, BqCrcEnabled, 5> = Bq769x0::new(i2c_dev_for_bq, addr, 3, None);
        if probe.try_apply_config(&cfg_template).await.is_ok() {
            defmt::info!("bq:0x{:02x}", addr);
            crate::failsafe::set_bq_online(true);
            bq_init_addr = Some(addr);
            break 'addr_loop;
        }
    }
    if bq_init_addr.is_none() {
        crate::failsafe::set_bq_online(false);
        defmt::warn!("bq:init failed within 500ms");
    }

    // 初始化完成后再启动相关任务（IRQ → LED → SC → BQ main）
    let sc_int = ExtiInput::new(p.PB2, p.EXTI2, Pull::Up);
    _spawner.spawn(sc8815_task::sc8815_irq_task(sc_int).expect("sc-int token"));

    let bq_alert = ExtiInput::new(p.PB1, p.EXTI1, Pull::None);
    _spawner.spawn(bq76920_task::bq_alert_irq_task(bq_alert).expect("bq-int token"));

    let led_r = Output::new(p.PA5, Level::High, Speed::Low);
    let led_y = Output::new(p.PA6, Level::High, Speed::Low);
    let led_g = Output::new(p.PA7, Level::High, Speed::Low);
    let led_b = Output::new(p.PB0, Level::High, Speed::Low);
    let led_bq_sub = bq76920_meas_chan
        .subscriber()
        .expect("Allocate BQ76920 measurements subscriber for 4-LED task");
    let led_sc_alerts_sub = _sc8815_alerts_chan
        .subscriber()
        .expect("Allocate SC8815 alerts subscriber for 4-LED task");
    let led_bq_alerts_sub = _bq76920_alerts_chan
        .subscriber()
        .expect("Allocate BQ76920 alerts subscriber for 4-LED task");
    let led_bal_cv_sub = balancing_cv_chan
        .subscriber()
        .expect("Allocate BalancingCv subscriber for 4-LED task");
    _spawner.spawn(
        leds4_task::leds_task(
            leds4_task::LedPins {
                red: led_r,
                yellow: led_y,
                green: led_g,
                blue: led_b,
            },
            led_bq_sub,
            led_sc_alerts_sub,
            led_bq_alerts_sub,
            led_bal_cv_sub,
        )
        .expect("led4 token"),
    );

    let bq76920_meas_sub = bq76920_meas_chan
        .subscriber()
        .expect("Allocate BQ76920 measurements subscriber");
    let i2c_dev_for_sc = I2cDevice::new(i2c_bus);
    let balancing_cv_sub = balancing_cv_chan
        .subscriber()
        .expect("Allocate BalancingCv subscriber for charger task");
    _spawner.spawn(
        sc8815_task::sc8815_task(sc8815_task::Sc8815TaskArgs {
            ce_ctl: ce,
            pstop_ctl: pstop,
            i2c_device: i2c_dev_for_sc,
            address: sc8815_task::SC8815_DEFAULT_ADDRESS,
            sc8815_alerts_publisher: sc8815_alerts_pub,
            sc8815_measurements_publisher: sc8815_meas_pub,
            bq76920_measurements_subscriber: bq76920_meas_sub,
            balancing_cv_sub,
        })
        .expect("sc token"),
    );

    let bq_runtime_addr = bq_init_addr.unwrap_or(BQ76920_I2C_ADDR);
    let i2c_dev_runtime = I2cDevice::new(i2c_bus);
    let sc8815_alerts_sub = _sc8815_alerts_chan
        .subscriber()
        .expect("Allocate SC8815 alerts subscriber for BQ task");
    _spawner.spawn(
        bq76920_task::bq76920_task(bq76920_task::Bq76920TaskArgs {
            i2c_bus: i2c_dev_runtime,
            address: bq_runtime_addr,
            sense_resistor_m_ohm: 3,
            ntc_params: None,
            bq76920_alerts_publisher: bq76920_alerts_pub,
            bq76920_measurements_publisher: bq76920_meas_pub,
            sc8815_alerts_subscriber: sc8815_alerts_sub,
            balancing_cv_publisher: balancing_cv_pub,
        })
        .expect("bq token"),
    );

    // 保留软件睡眠管理器（轻度 SLEEP 策略），由默认执行器 WFE 驱动。
    _spawner.spawn(sleep_manager::sleep_task().expect("sleep-mgr token"));

    // 电源静默策略改由 SC 路径直接更新至 failsafe，不再单独起调度任务

    // (Optional) EXTI for BQ ALERT can be enabled here if needed for additional wake sources.

    // Spawn合并后的 I2C1 从机 + 两路镜像状态机任务（保持日志与寄存器映射不变）
    _spawner.spawn(
        i2c1_slave::slave_mux_task(i2c1_dev, sc8815_meas_chan, bq76920_meas_chan)
            .expect("i2c1-mux token"),
    );
    // (omit gs_mirror_task to reduce flash)

    // Idle task: periodically yield; low-power executor controls STOP entry.
    loop {
        Timer::after(Duration::from_secs(1)).await;
    }
}
// 入口由 #[embassy_executor::main] 提供（线程模式 WFE）。
