#![no_std]
#![no_main]

mod bq76920_task;
mod data_types;
mod global_state;
mod i2c1_slave;
mod led_status_task;
mod sc8815_task;
mod scheduler;
mod shared;
mod sleep_manager;

use bq769x0_async_rs::{BatteryConfig, Bq769x0, Enabled as BqCrcEnabled, ProtectionConfig};
use defmt::info;
use embassy_embedded_hal::shared_bus::asynch::i2c::I2cDevice;
use embassy_executor::Spawner;
use embassy_stm32::interrupt::typelevel::Interrupt as _;
use embassy_stm32::{
    bind_interrupts,
    gpio::{Level, Output, OutputOpenDrain, Speed},
    i2c::{self, Config as I2cConfig, I2c, SlaveAddrConfig},
    peripherals::{I2C1, I2C2},
    time::Hertz,
};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::mutex::Mutex;
use embassy_time::{Duration, Timer};
use embassy_stm32::{exti::ExtiInput, gpio::Pull};
use static_cell::StaticCell;

// Fixed I2C address for BQ7692003PWR (7‑bit).
// Per TI device comparison table: the "03" variant uses CRC and a fixed
// I2C address 0x08. Other orderable numbers (e.g. BQ7692006) use 0x18.
const BQ76920_I2C_ADDR: u8 = 0x08;
use {defmt_rtt as _, panic_probe as _};

// (no build-id marker to save flash)

bind_interrupts!(struct I2c2Irqs {
    I2C2 => i2c::EventInterruptHandler<I2C2>, i2c::ErrorInterruptHandler<I2C2>;
});

// Bind I2C1 interrupts so the slave listen/respond paths can wake properly.
bind_interrupts!(struct I2c1Irqs {
    I2C1 => i2c::EventInterruptHandler<I2C1>, i2c::ErrorInterruptHandler<I2C1>;
});

#[embassy_executor::main]
async fn main(_spawner: Spawner) {
    let mut config = embassy_stm32::Config::default();
    config.rcc.ls = embassy_stm32::rcc::LsConfig::default_lse();
    // Single firmware profile: keep debug disabled during sleep for lowest current.
    config.enable_debug_during_sleep = false;
    let p = embassy_stm32::init(config);

    // 使用默认线程模式执行器：WFE 进入轻度 SLEEP（非 STOP）。
    // 启动日志（必须打印，复用与 sleep_task 相同的格式字符串以节省 FLASH）。
    defmt::warn!("sleep: start (mode=SLEEP)");

    // (Removed: APB1SMENR diagnostics to save flash)

    // Configure external I2C1 slave (PB6/PB7 @0x35) using embassy API only.
    // Ensure NVIC line is unmasked so I2C interrupts can wake from SLEEP.
    unsafe {
        #[allow(non_snake_case)]
        {
            // Type-level NVIC handle is generated by embassy for this MCU.
            embassy_stm32::interrupt::typelevel::I2C1::unpend();
            embassy_stm32::interrupt::typelevel::I2C1::enable();
        }
    }
    let mut i2c1_cfg = I2cConfig::default();
    i2c1_cfg.frequency = Hertz(100_000);
    let i2c1_blocking = I2c::new_blocking(p.I2C1, p.PB6, p.PB7, i2c1_cfg);
    let i2c1_dev = i2c1_blocking.into_slave_multimaster(SlaveAddrConfig::basic(0x35));
    // (Optional: I2C1.CR1.WUPEN for wake-from-STOP is omitted to save flash; RTC remains primary wake source.)

    // Keep SC8815 power stage disabled during configuration.
    let ce = Output::new(p.PA10, Level::High, Speed::Low);
    let pstop = Output::new(p.PA9, Level::High, Speed::Low);
    let mut exit_shipmode = Output::new(p.PA1, Level::Low, Speed::Low);
    // BQ76920 may power-up in SHIP; assert wake pin early to bring it to NORMAL.
    info!("bq:wake");
    exit_shipmode.set_high();
    Timer::after(Duration::from_millis(1200)).await;
    exit_shipmode.set_low();

    // (Removed: raw I2C1 PAC readbacks to save flash)

    // Prepare INNER I2C bus (I2C2 on PB10/PB11) with 100 kHz clock and wrap as shared bus.
    // Ensure I2C2 NVIC is unmasked to avoid async transactions stalling.
    unsafe {
        #[allow(non_snake_case)]
        {
            embassy_stm32::interrupt::typelevel::I2C2::unpend();
            embassy_stm32::interrupt::typelevel::I2C2::enable();
        }
    }
    let mut i2c_config = I2cConfig::default();
    i2c_config.frequency = Hertz(100_000);
    let i2c = I2c::new(
        p.I2C2, p.PB10, p.PB11, I2c2Irqs, p.DMA1_CH4, p.DMA1_CH5, i2c_config,
    );
    type I2c2Bus =
        Mutex<CriticalSectionRawMutex, I2c<'static, embassy_stm32::mode::Async, i2c::mode::Master>>;
    static I2C2_BUS: StaticCell<I2c2Bus> = StaticCell::new();
    let i2c_bus: &'static I2c2Bus = I2C2_BUS.init(Mutex::new(i2c));

    // Initialize pubsub channels and get publishers for BQ76920 task
    let (
        _measurements_pub,
        _measurements_chan,
        sc8815_alerts_pub,
        _sc8815_alerts_chan,
        bq76920_alerts_pub,
        _bq76920_alerts_chan,
        sc8815_meas_pub,
        sc8815_meas_chan,
        bq76920_meas_pub,
        bq76920_meas_chan,
        balancing_cv_pub,
        balancing_cv_chan,
        global_state_pub,
        global_state_chan,
    ) = shared::init_pubsubs();

    // Gate other tasks on successful BQ76920 initialization using fixed I2C address.
    info!("bq:init");
    let mut ship_mode_pulsed = true; // already pulsed once at boot
    let mut retry_count: u32 = 0;
    let _selected_bq_addr = loop {
        // Try common fixed-address variants: 0x08 (03) then 0x18 (06)
        let tried: [u8; 2] = [BQ76920_I2C_ADDR, 0x18u8];
        let mut ok_addr: Option<u8> = None;
        for addr in tried.iter().copied() {
            defmt::debug!("bq:try=0x{:02x}", addr);
            let cfg = BatteryConfig {
            overvoltage_trip: 3650,  // 3.65V per cell
            undervoltage_trip: 2500, // 2.50V per cell
            protection_config: ProtectionConfig {
                scd_limit: 15_000, // 15A short-circuit
                ocd_limit: 10_000, // 10A overcurrent
                ..BatteryConfig::default().protection_config
            },
            rsense: 3, // 3 mΩ sense resistor
            ..Default::default()
        };
            let i2c_dev_for_bq = I2cDevice::new(i2c_bus);
            let mut bq: Bq769x0<_, BqCrcEnabled, 5> = Bq769x0::new(i2c_dev_for_bq, addr, 3, None);
            if bq.try_apply_config(&cfg).await.is_ok() {
                ok_addr = Some(addr);
                break;
            }
        }
        if let Some(ok) = ok_addr {
    info!("bq:0x{:02x}", ok);
            // Spawn the continuous BQ76920 task now that init succeeded.
            let i2c_dev_runtime = I2cDevice::new(i2c_bus);
            let sc8815_alerts_sub = _sc8815_alerts_chan
                .subscriber()
                .expect("Allocate SC8815 alerts subscriber for BQ task");
            _spawner
                .spawn(
                    bq76920_task::bq76920_task(
                        i2c_dev_runtime,
                        ok,
                        3,    // sense resistor mΩ
                        None, // no NTC parameters provided
                        bq76920_alerts_pub,
                        bq76920_meas_pub,
                        sc8815_alerts_sub,
                        balancing_cv_pub,
                    )
                    .expect("bq token"),
                );
            break ok;
        }
        // periodic retry with occasional wake pulse refresh
        retry_count = retry_count.wrapping_add(1);
        if (retry_count % 3) == 0 {
            defmt::debug!("bq:wake+");
            exit_shipmode.set_high();
            Timer::after(Duration::from_millis(300)).await;
            exit_shipmode.set_low();
        }
        if (retry_count % 5) == 0 {
            info!("bq:r");
        }
        defmt::debug!("bq:retry");
        Timer::after(Duration::from_secs(1)).await;
    };

    // Create a subscriber for BQ76920 measurements to feed charger control logic.
    let bq76920_meas_sub = bq76920_meas_chan
        .subscriber()
        .expect("Allocate BQ76920 measurements subscriber");

    // Spawn SC8815 charger management task now that the protection IC is live.
    let i2c_dev_for_sc = I2cDevice::new(i2c_bus);
    let balancing_cv_sub = balancing_cv_chan
        .subscriber()
        .expect("Allocate BalancingCv subscriber for charger task");
    _spawner.spawn(
        sc8815_task::sc8815_task(
            ce,
            pstop,
            exit_shipmode,
            i2c_dev_for_sc,
            sc8815_task::SC8815_DEFAULT_ADDRESS,
            sc8815_alerts_pub,
            sc8815_meas_pub,
            bq76920_meas_sub,
            balancing_cv_sub,
        )
        .expect("sc token"),
    );

    // SC8815 INT: per README mapping PB2 = INNER_INT (EXTI2)
    let sc_int = ExtiInput::new(p.PB2, p.EXTI2, Pull::Up);
    _spawner
        .spawn(sc8815_task::sc8815_irq_task(sc_int).expect("sc-int token"));

    // BQ76920 ALERT: PB1 = ALERT (EXTI1). Datasheet: push-pull active-high → no pull.
    let bq_alert = ExtiInput::new(p.PB1, p.EXTI1, Pull::None);
    _spawner
        .spawn(bq76920_task::bq_alert_irq_task(bq_alert).expect("bq-int token"));

    // 启动 Global State 聚合任务
    let gs_sc_alerts_sub = _sc8815_alerts_chan
        .subscriber()
        .expect("Allocate SC8815 alerts subscriber for GS task");
    let gs_sc_meas_sub = sc8815_meas_chan
        .subscriber()
        .expect("Allocate SC8815 measurements subscriber for GS task");
    let gs_bq_alerts_sub = _bq76920_alerts_chan
        .subscriber()
        .expect("Allocate BQ76920 alerts subscriber for GS task");
    let gs_bal_cv_sub = balancing_cv_chan
        .subscriber()
        .expect("Allocate BalancingCv subscriber for GS task");
    let gs_bq_meas_sub = bq76920_meas_chan
        .subscriber()
        .expect("Allocate BQ76920 measurements subscriber for GS task");
    _spawner.spawn(
        global_state::global_state_task(
            gs_sc_alerts_sub,
            gs_sc_meas_sub,
            gs_bq_alerts_sub,
            gs_bal_cv_sub,
            gs_bq_meas_sub,
            global_state_pub,
        )
        .expect("gs token"),
    );

    // 启动 LED 状态任务（需要用户可见的状态指示）
    let mut led_pin = OutputOpenDrain::new(p.PA5, Level::High, Speed::Low);
    // Boot heartbeat: 两次短闪，确保即便 RTT 无输出也能肉眼确认 MCU 已运行。
    for _ in 0..2u8 {
        led_pin.set_low();
        Timer::after(Duration::from_millis(80)).await;
        led_pin.set_high();
        Timer::after(Duration::from_millis(120)).await;
    }
    let led_global_state_sub = global_state_chan
        .subscriber()
        .expect("Allocate GlobalState subscriber for LED task");
    _spawner
        .spawn(led_status_task::led_status_task(led_pin, led_global_state_sub).expect("led token"));

    // 保留软件睡眠管理器（轻度 SLEEP 策略），由默认执行器 WFE 驱动。
    _spawner.spawn(sleep_manager::sleep_task().expect("sleep-mgr token"));

    let gs_sub_for_sched = global_state_chan
        .subscriber()
        .expect("Allocate GS subscriber for scheduler");
    _spawner.spawn(scheduler::power_scheduler_task(gs_sub_for_sched).expect("sched token"));

    // (Optional) EXTI for BQ ALERT can be enabled here if needed for additional wake sources.

    // Spawn I2C1 slave + snapshot mirror tasks for the external interface
    _spawner.spawn(i2c1_slave::slave_task(i2c1_dev).expect("slave token"));
    _spawner.spawn(i2c1_slave::sc_meas_mirror_task(sc8815_meas_chan).expect("sc-mirror token"));
    _spawner.spawn(i2c1_slave::bq_meas_mirror_task(bq76920_meas_chan).expect("bq-mirror token"));
    // (omit gs_mirror_task to reduce flash)

    // Idle task: periodically yield; low-power executor controls STOP entry.
    loop {
        Timer::after(Duration::from_secs(1)).await;
    }
}
// 入口由 #[embassy_executor::main] 提供（线程模式 WFE）。
