[package]
name = "ups-main"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# I2C master demo stack
embedded-hal = "1.0.0"
esp-hal = { version = "1.0.0-rc.1", features = ["esp32s3", "unstable"] }
esp-backtrace = { version = "0.17.0", features = ["esp32s3", "panic-handler", "println"] }
esp-println = { version = "0.15.0", features = ["esp32s3", "defmt-espflash"] }
esp-bootloader-esp-idf = { version = "0.2.0", features = ["esp32s3"] }

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
lto = "fat"
opt-level = "s"
overflow-checks = false
