[workspace]
members = [
  "firmware/smart-battery",
  "firmware/ups-main",
]
resolver = "3"
default-members = [
  "firmware/smart-battery"
]



 [workspace.package]
 edition = "2024"
 version = "0.1.0"
 authors = ["Ivan Li<ivanli2048@gmail.com>"]

[workspace.dependencies]
embassy-stm32 = { version = "0.2.0", path = "./embassy/embassy-stm32" }
 embassy-sync = { version = "0.7.0", path = "./embassy/embassy-sync" }
 embassy-executor = { version = "0.7.0", path = "./embassy/embassy-executor" }
 embassy-time = { version = "0.4.0", path = "./embassy/embassy-time" }
 embassy-usb = { version = "0.4.0", path = "./embassy/embassy-usb" }
 embassy-futures = { version = "0.1.0", path = "./embassy/embassy-futures" }
 embassy-embedded-hal = { version = "0.3.0", path = "./embassy/embassy-embedded-hal" }
 defmt = "1.0.1"
 defmt-rtt = "1.0.0"
 cortex-m = { version = "0.7.7" }
 cortex-m-rt = "0.7.5"
 embedded-hal = "1.0.0"
 panic-probe = { version = "1.0.0", features = ["print-defmt"] }
 heapless = { version = "0.8", default-features = false }
 portable-atomic = { version = "1.11.0", features = ["critical-section"] }
 static_cell = "2.1.0"
 libm = "0.2.8"
 embedded-alloc = "0.6.0"
 embedded-io-async = { version = "0.6.1" }
 binrw = { version = "0.15", default-features = false }
 bq769x0-async-rs = { version = "*", path = "./bq76920" }
sc8815 = { version = "*", path = "./sc8815" }
ina226 = { version = "0.3.0" }

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = "thin"
opt-level = "z"
overflow-checks = false
panic = "abort"

[workspace.lints.rust]
unused = "allow"
