[package]
name = "smart-battery"
version = "0.1.0"
edition = "2024"
authors = ["Ivan Li<ivanli2048@gmail.com>"]

[dependencies]
embassy-stm32 = { path = "../../embassy/embassy-stm32", features = [
  "defmt",
  "time-driver-any",
  "stm32l051c8",
  "memory-x",
  "exti",
  "unstable-pac",
] }
embassy-sync = { path = "../../embassy/embassy-sync", features = ["defmt"] }
embassy-executor = { path = "../../embassy/embassy-executor", features = [
  "arch-cortex-m",
  "executor-thread",
  "defmt",
] }
embassy-time = { path = "../../embassy/embassy-time", features = [
  "defmt",
  "defmt-timestamp-uptime",
  "tick-hz-32_768",
] }
sc8815 = { path = "../../sc8815", features = ["async", "defmt"] }
defmt = "1.0.1"
defmt-rtt = "1.0.0"
embassy-embedded-hal = { path = "../../embassy/embassy-embedded-hal" }
bq769x0-async-rs = { path = "../../bq76920", features = ["async", "defmt"] }
static_cell = "2.1.0"
portable-atomic = { version = "1.11.0", features = ["critical-section"] }
heapless = { version = "0.9.1", default-features = false }
critical-section = "1.1"
## binrw not required in firmware (avoid pulling alloc)

cortex-m = { version = "0.7.7", features = [
  "critical-section-single-core",
] }
cortex-m-rt = "0.7.5"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
## no dynamic allocation required in firmware

[[bin]]
name = "smart-battery"
path = "src/main.rs"
test = false

[profile.dev]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 'z'
overflow-checks = false
panic = 'abort'

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 'z'
overflow-checks = false
panic = 'abort'
