use core::fmt::Write as _;

use embedded_hal::{delay::DelayNs, digital::OutputPin, spi::SpiBus};

use crate::display::{
    clear_framebuffer, fill_rect_buffer, flush_framebuffer, put_pixel_buffer, with_framebuffer,
    FrameBuffer, Rgb565, LOGICAL_HEIGHT, LOGICAL_WIDTH,
};

// Palette (RGB565)
const BLACK: Rgb565 = Rgb565(0x0000);
const WHITE: Rgb565 = Rgb565(0xFFFF);
const GRAY: Rgb565 = Rgb565(0x8410);
const GREEN: Rgb565 = Rgb565(0x07E0); // Power
const YELLOW: Rgb565 = Rgb565(0xFFE0);
const ORANGE: Rgb565 = Rgb565(0xFD20); // Voltage
const RED: Rgb565 = Rgb565(0xF800); // Current
const CYAN: Rgb565 = Rgb565(0x07FF); // Labels
const PLACEHOLDER: &str = "--";

// Layout
const MARGIN_LR: u16 = 4;
const MARGIN_TB: u16 = 1;
const LINE_H: u16 = 12; // 7x10 glyph + 2px leading
const GLYPH_W: u16 = 7;
const GLYPH_H: usize = 10;
const GLYPH_H_U16: u16 = GLYPH_H as u16;
const CELL_W: u16 = 8;

const LABEL_WIDTH_CELLS: usize = 4;
const VALUE_GAP_CELLS: usize = 1;
const VOLT_WIDTH_CELLS: usize = 5;
const CURRENT_WIDTH_CELLS: usize = 4;
const POWER_WIDTH_CELLS: usize = 4;

const TEMP_LABEL_CELLS: usize = 4;
const TEMP_VALUE_CELLS: usize = 4;
const AUX_GAP_CELLS: usize = 3;
const FAN_LABEL_CELLS: usize = 3;
const FAN_VALUE_CELLS: usize = 4;

const COL_LABEL: usize = 0;
const COL_VOLT: usize = LABEL_WIDTH_CELLS;
const COL_CURR: usize = COL_VOLT + VOLT_WIDTH_CELLS + VALUE_GAP_CELLS;
const COL_POWER: usize = COL_CURR + CURRENT_WIDTH_CELLS + VALUE_GAP_CELLS;

const AUX_TEMP_VALUE_COL: usize = TEMP_LABEL_CELLS;
const AUX_FAN_LABEL_COL: usize = TEMP_LABEL_CELLS + TEMP_VALUE_CELLS + AUX_GAP_CELLS;
const AUX_FAN_VALUE_COL: usize = AUX_FAN_LABEL_COL + FAN_LABEL_CELLS;

// 7x10 bitmap glyphs generated by scaling the previous 5x7 UI set.
fn glyph(c: u8) -> Option<&'static [u8; GLYPH_H]> {
    match c {
        b' ' => Some(&[
            0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0000000,
            0b0000000, 0b0000000,
        ]),
        b'%' => Some(&[
            0b1110000, 0b1110001, 0b1110001, 0b0000110, 0b0001000, 0b0001000, 0b0110000, 0b1000111,
            0b1000111, 0b0000111,
        ]),
        b'-' => Some(&[
            0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0111110, 0b0111110, 0b0000000, 0b0000000,
            0b0000000, 0b0000000,
        ]),
        b'.' => Some(&[
            0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0000000, 0b0001000,
            0b0001000, 0b0001000,
        ]),
        b'0' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b1000111, 0b1001001, 0b1001001, 0b1110001, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'1' => Some(&[
            0b0001000, 0b0111000, 0b0111000, 0b0001000, 0b0001000, 0b0001000, 0b0001000, 0b0001000,
            0b0001000, 0b0111110,
        ]),
        b'2' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b0000001, 0b0000110, 0b0000110, 0b0001000, 0b0110000,
            0b0110000, 0b1111111,
        ]),
        b'3' => Some(&[
            0b1111110, 0b0000001, 0b0000001, 0b0000001, 0b0111110, 0b0111110, 0b0000001, 0b0000001,
            0b0000001, 0b1111110,
        ]),
        b'4' => Some(&[
            0b0000110, 0b0001110, 0b0001110, 0b0110110, 0b1000110, 0b1000110, 0b1111111, 0b0000110,
            0b0000110, 0b0000110,
        ]),
        b'5' => Some(&[
            0b1111111, 0b1000000, 0b1000000, 0b1111110, 0b0000001, 0b0000001, 0b0000001, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'6' => Some(&[
            0b0001110, 0b0110000, 0b0110000, 0b1000000, 0b1111110, 0b1111110, 0b1000001, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'7' => Some(&[
            0b1111111, 0b0000001, 0b0000001, 0b0000110, 0b0001000, 0b0001000, 0b0110000, 0b0110000,
            0b0110000, 0b0110000,
        ]),
        b'8' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b1000001, 0b0111110, 0b0111110, 0b1000001, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'9' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b1000001, 0b0111111, 0b0111111, 0b0000001, 0b0000110,
            0b0000110, 0b0111000,
        ]),
        b':' => Some(&[
            0b0000000, 0b0001000, 0b0001000, 0b0001000, 0b0000000, 0b0000000, 0b0001000, 0b0001000,
            0b0001000, 0b0000000,
        ]),
        b'A' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b1000001, 0b1111111, 0b1111111, 0b1000001, 0b1000001,
            0b1000001, 0b1000001,
        ]),
        b'B' => Some(&[
            0b1111110, 0b1000001, 0b1000001, 0b1000001, 0b1111110, 0b1111110, 0b1000001, 0b1000001,
            0b1000001, 0b1111110,
        ]),
        b'C' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b1000000, 0b1000000, 0b1000000, 0b1000000, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'D' => Some(&[
            0b1111000, 0b1000110, 0b1000110, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000110,
            0b1000110, 0b1111000,
        ]),
        b'E' => Some(&[
            0b1111111, 0b1000000, 0b1000000, 0b1000000, 0b1111110, 0b1111110, 0b1000000, 0b1000000,
            0b1000000, 0b1111111,
        ]),
        b'F' => Some(&[
            0b1111111, 0b1000000, 0b1000000, 0b1000000, 0b1111110, 0b1111110, 0b1000000, 0b1000000,
            0b1000000, 0b1000000,
        ]),
        b'G' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b1000000, 0b1001111, 0b1001111, 0b1000001, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'H' => Some(&[
            0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1111111, 0b1111111, 0b1000001, 0b1000001,
            0b1000001, 0b1000001,
        ]),
        b'I' => Some(&[
            0b0111110, 0b0001000, 0b0001000, 0b0001000, 0b0001000, 0b0001000, 0b0001000, 0b0001000,
            0b0001000, 0b0111110,
        ]),
        b'L' => Some(&[
            0b1000000, 0b1000000, 0b1000000, 0b1000000, 0b1000000, 0b1000000, 0b1000000, 0b1000000,
            0b1000000, 0b1111111,
        ]),
        b'M' => Some(&[
            0b1000001, 0b1110111, 0b1110111, 0b1001001, 0b1001001, 0b1001001, 0b1000001, 0b1000001,
            0b1000001, 0b1000001,
        ]),
        b'N' => Some(&[
            0b1000001, 0b1000001, 0b1000001, 0b1110001, 0b1001001, 0b1001001, 0b1000111, 0b1000001,
            0b1000001, 0b1000001,
        ]),
        b'O' => Some(&[
            0b0111110, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'P' => Some(&[
            0b1111110, 0b1000001, 0b1000001, 0b1000001, 0b1111110, 0b1111110, 0b1000000, 0b1000000,
            0b1000000, 0b1000000,
        ]),
        b'R' => Some(&[
            0b1111110, 0b1000001, 0b1000001, 0b1000001, 0b1111110, 0b1111110, 0b1001000, 0b1000110,
            0b1000110, 0b1000001,
        ]),
        b'S' => Some(&[
            0b0111111, 0b1000000, 0b1000000, 0b1000000, 0b0111110, 0b0111110, 0b0000001, 0b0000001,
            0b0000001, 0b1111110,
        ]),
        b'T' => Some(&[
            0b1111111, 0b0001000, 0b0001000, 0b0001000, 0b0001000, 0b0001000, 0b0001000, 0b0001000,
            0b0001000, 0b0001000,
        ]),
        b'U' => Some(&[
            0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001,
            0b1000001, 0b0111110,
        ]),
        b'V' => Some(&[
            0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b1000001, 0b0110110, 0b0110110,
            0b0110110, 0b0001000,
        ]),
        b'W' => Some(&[
            0b1000001, 0b1000001, 0b1000001, 0b1001001, 0b1001001, 0b1001001, 0b1001001, 0b1110111,
            0b1110111, 0b1000001,
        ]),
        b'Y' => Some(&[
            0b1000001, 0b1000001, 0b1000001, 0b0110110, 0b0001000, 0b0001000, 0b0001000, 0b0001000,
            0b0001000, 0b0001000,
        ]),
        _ => None,
    }
}

fn draw_char(fb: &mut FrameBuffer, x: u16, y: u16, ch: u8, color: Rgb565) -> u16 {
    if let Some(rows) = glyph(ch) {
        for (ry, row) in rows.iter().enumerate() {
            let mut mask = 1u8 << (GLYPH_W as u8 - 1);
            for rx in 0..GLYPH_W {
                if (row & mask) != 0 {
                    put_pixel_buffer(fb, x + rx, y + ry as u16, color);
                }
                mask >>= 1;
            }
        }
    } else {
        for rx in 0..GLYPH_W {
            put_pixel_buffer(fb, x + rx, y, color);
            put_pixel_buffer(fb, x + rx, y + GLYPH_H_U16 - 1, color);
        }
        for ry in 0..GLYPH_H {
            let ry = ry as u16;
            put_pixel_buffer(fb, x, y + ry, color);
            put_pixel_buffer(fb, x + GLYPH_W - 1, y + ry, color);
        }
    }
    CELL_W
}

fn draw_text(fb: &mut FrameBuffer, mut x: u16, y: u16, s: &str, color: Rgb565) -> u16 {
    for &b in s.as_bytes() {
        x += draw_char(fb, x, y, b.to_ascii_uppercase(), color);
    }
    x
}

fn draw_text_clipped(
    fb: &mut FrameBuffer,
    mut x: u16,
    y: u16,
    s: &str,
    color: Rgb565,
    max_width_px: u16,
) -> u16 {
    let start_x = x;
    for &b in s.as_bytes() {
        if x.saturating_sub(start_x) + CELL_W > max_width_px {
            break;
        }
        x += draw_char(fb, x, y, b.to_ascii_uppercase(), color);
    }
    x
}

fn text_width(s: &str) -> u16 {
    (s.as_bytes().len() as u16) * CELL_W
}

fn center_x(s: &str) -> u16 {
    let w = text_width(s);
    let cw = LOGICAL_WIDTH;
    let x = (cw.saturating_sub(w)) / 2;
    x.max(MARGIN_LR)
}

fn cell_to_x(cell: usize) -> u16 {
    MARGIN_LR + (cell as u16) * CELL_W
}

fn draw_value_right(
    fb: &mut FrameBuffer,
    col_start: usize,
    width_cells: usize,
    y: u16,
    text: &str,
    color: Rgb565,
) -> u16 {
    let text_cells = text.as_bytes().len();
    let start_cell = if text_cells >= width_cells {
        col_start
    } else {
        col_start + (width_cells - text_cells)
    };
    let x = cell_to_x(start_cell);
    draw_text(fb, x, y, text, color)
}

fn draw_celsius(fb: &mut FrameBuffer, x: u16, y: u16, color: Rgb565) -> u16 {
    let dot_x = x;
    let dot_y = if y > 0 { y - 1 } else { y };
    fill_rect_buffer(fb, dot_x, dot_y, dot_x + 1, dot_y + 1, color);
    draw_char(fb, x + 4, y, b'C', color)
}

// ---------------- Boot Screen -----------------
pub fn render_boot<SPI, CS, DC, DLY>(
    spi: &mut SPI,
    cs: &mut CS,
    dc: &mut DC,
    delay: &mut DLY,
) -> Result<(), SPI::Error>
where
    SPI: SpiBus<u8>,
    CS: OutputPin,
    DC: OutputPin,
    DLY: DelayNs,
{
    clear_framebuffer(BLACK);
    with_framebuffer(|fb| {
        let title = "UPS120";
        let y0 = MARGIN_TB;
        draw_text(fb, center_x(title), y0, title, WHITE);

        let subtitle = "SYSTEM BOOT";
        let y1 = y0 + LINE_H;
        draw_text(fb, center_x(subtitle), y1, subtitle, GRAY);

        let bar_w = LOGICAL_WIDTH - 2 * MARGIN_LR;
        let bar_h: u16 = 8;
        let bar_x = MARGIN_LR;
        let bar_y = LOGICAL_HEIGHT - MARGIN_TB - bar_h - LINE_H; // reserve 1 text line above

        let left = bar_x.saturating_sub(1);
        let right = (bar_x + bar_w).min(LOGICAL_WIDTH - 1);
        let top = bar_y.saturating_sub(1);
        let bottom = (bar_y + bar_h).min(LOGICAL_HEIGHT - 1);
        fill_rect_buffer(fb, left, top, right, top, GRAY);
        fill_rect_buffer(fb, left, bottom, right, bottom, GRAY);
        fill_rect_buffer(fb, left, top, left, bottom, GRAY);
        fill_rect_buffer(fb, right, top, right, bottom, GRAY);
    });
    flush_framebuffer(spi, cs, dc)?;

    let bar_w = LOGICAL_WIDTH - 2 * MARGIN_LR;
    let bar_h: u16 = 8;
    let bar_x = MARGIN_LR;
    let bar_y = LOGICAL_HEIGHT - MARGIN_TB - bar_h - LINE_H;

    for pct in (0..=100).step_by(5) {
        let fill = (u32::from(bar_w) * pct as u32 / 100) as u16;
        with_framebuffer(|fb| {
            fill_rect_buffer(
                fb,
                bar_x,
                bar_y,
                bar_x + bar_w - 1,
                bar_y + bar_h - 1,
                BLACK,
            );
            if fill > 0 {
                fill_rect_buffer(fb, bar_x, bar_y, bar_x + fill - 1, bar_y + bar_h - 1, GREEN);
            }

            let mut buf = heapless::String::<32>::new();
            let _ = write!(&mut buf, "INIT {}%", pct);
            fill_rect_buffer(
                fb,
                MARGIN_LR,
                bar_y - LINE_H,
                LOGICAL_WIDTH - MARGIN_LR - 1,
                bar_y - 1,
                BLACK,
            );
            draw_text(fb, center_x(&buf), bar_y - LINE_H, &buf, WHITE);
        });
        flush_framebuffer(spi, cs, dc)?;
        delay.delay_ms(40);
    }

    delay.delay_ms(400);
    Ok(())
}

// ---------------- Dashboard -----------------
#[derive(Clone, Copy)]
pub enum Mode {
    Standby,
    Charge,
    Discharge,
}

// ---------------- Boot Progress (staged) -----------------
/// Draw static boot frame (title + empty progress bar), without animation.
pub fn boot_init_begin<SPI, CS, DC>(
    spi: &mut SPI,
    cs: &mut CS,
    dc: &mut DC,
) -> Result<(), SPI::Error>
where
    SPI: SpiBus<u8>,
    CS: OutputPin,
    DC: OutputPin,
{
    clear_framebuffer(BLACK);
    with_framebuffer(|fb| {
        let title = "UPS120";
        let y0 = MARGIN_TB;
        draw_text(fb, center_x(title), y0, title, WHITE);

        let subtitle = "SYSTEM BOOT";
        let y1 = y0 + LINE_H;
        draw_text(fb, center_x(subtitle), y1, subtitle, GRAY);

        let bar_w = LOGICAL_WIDTH - 2 * MARGIN_LR;
        let bar_h: u16 = 8;
        let bar_x = MARGIN_LR;
        let bar_y = LOGICAL_HEIGHT - MARGIN_TB - bar_h - LINE_H;

        let left = bar_x.saturating_sub(1);
        let right = (bar_x + bar_w).min(LOGICAL_WIDTH - 1);
        let top = bar_y.saturating_sub(1);
        let bottom = (bar_y + bar_h).min(LOGICAL_HEIGHT - 1);
        fill_rect_buffer(fb, left, top, right, top, GRAY);
        fill_rect_buffer(fb, left, bottom, right, bottom, GRAY);
        fill_rect_buffer(fb, left, top, left, bottom, GRAY);
        fill_rect_buffer(fb, right, top, right, bottom, GRAY);
    });
    flush_framebuffer(spi, cs, dc)
}

/// Update boot progress bar and a single-line label above it.
pub fn boot_update<SPI, CS, DC>(
    spi: &mut SPI,
    cs: &mut CS,
    dc: &mut DC,
    pct: u8,
    label: &str,
) -> Result<(), SPI::Error>
where
    SPI: SpiBus<u8>,
    CS: OutputPin,
    DC: OutputPin,
{
    let bar_w = LOGICAL_WIDTH - 2 * MARGIN_LR;
    let bar_h: u16 = 8;
    let bar_x = MARGIN_LR;
    let bar_y = LOGICAL_HEIGHT - MARGIN_TB - bar_h - LINE_H;

    let fill = (u32::from(bar_w) * pct.min(100) as u32 / 100) as u16;
    with_framebuffer(|fb| {
        // clear bar area
        fill_rect_buffer(
            fb,
            bar_x,
            bar_y,
            bar_x + bar_w - 1,
            bar_y + bar_h - 1,
            BLACK,
        );
        // fill progress
        if fill > 0 {
            fill_rect_buffer(fb, bar_x, bar_y, bar_x + fill - 1, bar_y + bar_h - 1, GREEN);
        }
        // draw label line above bar
        let y_text = bar_y - LINE_H;
        fill_rect_buffer(
            fb,
            MARGIN_LR,
            y_text,
            LOGICAL_WIDTH - MARGIN_LR - 1,
            bar_y - 1,
            BLACK,
        );
        let x = center_x(label);
        draw_text(fb, x, y_text, label, WHITE);
    });
    flush_framebuffer(spi, cs, dc)
}

#[derive(Clone, Copy)]
pub enum TempSlot {
    Battery,
    Ups,
}

pub struct DashboardData {
    pub mode: Mode,
    pub soc_pct: u8,
    pub vbat_mv: Option<u32>,
    pub soc_display: SocDisplay,
    pub in_v_mv: u32,
    pub in_a_ma: u32,
    pub in_w_mw: u32,
    pub chg_w_mw: u32,
    pub out_v_mv: u32,
    pub out_a_ma: u32,
    pub out_w_mw: u32,
    pub bat_temp_c: i16,
    pub ups_temp_c: i16,
    pub fan_pct: u8,
    pub uptime_secs: u32,
    pub temp_slot: TempSlot,
}

fn fmt_voltage(mv: u32, buf: &mut heapless::String<16>) {
    buf.clear();
    let clamped = mv.min(99_990);
    let v_tenths = (clamped + 50) / 100; // 0.1V units
    let whole = v_tenths / 10;
    if whole >= 100 {
        let _ = buf.push_str(">99V");
        return;
    }
    let frac = v_tenths % 10;
    if whole >= 10 {
        let _ = write!(buf, "{:02}.{}V", whole, frac);
    } else {
        let hundredths = ((clamped + 5) / 10) % 10;
        let _ = write!(buf, "{}.{}{}V", whole, frac, hundredths);
    }
}

fn fmt_current(ma: u32, buf: &mut heapless::String<16>) {
    buf.clear();
    let clamped = ma.min(99_900);
    if clamped >= 10_000 {
        let amps = (clamped + 500) / 1000;
        if amps >= 100 {
            let _ = buf.push_str(">99A");
        } else {
            let _ = write!(buf, "{:>3}A", amps);
        }
    } else {
        let a_tenths = (clamped + 50) / 100;
        let whole = a_tenths / 10;
        let frac = a_tenths % 10;
        let _ = write!(buf, "{}.{}A", whole, frac);
    }
}

fn fmt_power(mw: u32, buf: &mut heapless::String<16>) {
    buf.clear();
    let w = (mw + 500) / 1000;
    if w > 999 {
        let _ = buf.push_str("999W");
    } else {
        let _ = write!(buf, "{:>3}W", w);
    }
}

fn fmt_soc<const N: usize>(pct: u8, buf: &mut heapless::String<N>) {
    buf.clear();
    let capped = pct.min(100);
    let _ = write!(buf, "{:>3}%", capped);
}

#[derive(Clone, Copy)]
pub enum SocDisplay {
    Percent,
    Voltage,
}

fn build_soc_text_and_color(
    soc: u8,
    vbat_mv: Option<u32>,
    which: SocDisplay,
) -> (heapless::String<16>, Rgb565) {
    let mut s: heapless::String<16> = heapless::String::new();
    match which {
        SocDisplay::Percent => {
            fmt_soc(soc, &mut s);
            let color = if soc <= 15 {
                RED
            } else if soc <= 30 {
                YELLOW
            } else {
                WHITE
            };
            (s, color)
        }
        SocDisplay::Voltage => {
            if let Some(mv) = vbat_mv {
                fmt_voltage(mv, &mut s);
                (s, ORANGE)
            } else {
                let _ = s.push_str(PLACEHOLDER);
                (s, GRAY)
            }
        }
    }
}

fn fmt_temp_digits(c: i16, buf: &mut heapless::String<8>) {
    buf.clear();
    let capped = c.clamp(-99, 199);
    let _ = write!(buf, "{}", capped);
}

fn fmt_fan(pct: u8, buf: &mut heapless::String<8>) {
    buf.clear();
    let capped = pct.min(100);
    let _ = write!(buf, "{:>3}%", capped);
}

fn fmt_uptime(secs: u32, buf: &mut heapless::String<16>) {
    buf.clear();
    const THRESHOLD: u32 = 72 * 3600;
    if secs < THRESHOLD {
        let h = secs / 3600;
        let m = (secs % 3600) / 60;
        let s = secs % 60;
        let _ = write!(buf, "{:02}:{:02}:{:02}", h, m, s);
    } else {
        let d = secs / 86400;
        let h = (secs % 86400) / 3600;
        let m = (secs % 3600) / 60;
        let _ = write!(buf, "{:02}D{:02}:{:02}", d, h, m);
    }
}

fn mode_text_and_color(mode: Mode) -> (&'static str, Rgb565) {
    match mode {
        Mode::Standby => ("MODE: STANDBY", GRAY),
        Mode::Charge => ("MODE: CHARGE", CYAN),
        Mode::Discharge => ("MODE: DISCHARGE", WHITE),
    }
}

fn draw_soc(fb: &mut FrameBuffer, y: u16, soc: u8) {
    let mut s: heapless::String<8> = heapless::String::new();
    fmt_soc(soc, &mut s);
    let color = if soc <= 15 {
        RED
    } else if soc <= 30 {
        YELLOW
    } else {
        WHITE
    };
    let x = LOGICAL_WIDTH - MARGIN_LR - text_width(&s);
    let _ = draw_text(fb, x, y, &s, color);
}

fn draw_trio_line(fb: &mut FrameBuffer, y: u16, head: &str, v: &str, a: &str, w: &str) {
    let _ = draw_text(fb, cell_to_x(COL_LABEL), y, head, CYAN);
    let volt_color = if v == PLACEHOLDER { GRAY } else { ORANGE };
    let curr_color = if a == PLACEHOLDER { GRAY } else { RED };
    let power_color = if w == PLACEHOLDER { GRAY } else { GREEN };
    let _ = draw_value_right(fb, COL_VOLT, VOLT_WIDTH_CELLS, y, v, volt_color);
    let _ = draw_value_right(fb, COL_CURR, CURRENT_WIDTH_CELLS, y, a, curr_color);
    let _ = draw_value_right(fb, COL_POWER, POWER_WIDTH_CELLS, y, w, power_color);
}

fn draw_aux_line(fb: &mut FrameBuffer, y: u16, slot: TempSlot, bat_c: i16, ups_c: i16, fan: u8) {
    let (label, temp) = match slot {
        TempSlot::Battery => ("BAT", bat_c),
        TempSlot::Ups => ("UPS", ups_c),
    };

    let temp_label_x = cell_to_x(COL_LABEL);
    let _ = draw_text(fb, temp_label_x, y, label, CYAN);

    let mut temp_digits: heapless::String<8> = heapless::String::new();
    fmt_temp_digits(temp, &mut temp_digits);
    let total_cells = temp_digits.as_bytes().len() + 1; // digits + 'C'
    let start_cell = if total_cells >= TEMP_VALUE_CELLS {
        AUX_TEMP_VALUE_COL
    } else {
        AUX_TEMP_VALUE_COL + (TEMP_VALUE_CELLS - total_cells)
    };
    let digits_x = cell_to_x(start_cell);
    let x_after_digits = draw_text(fb, digits_x, y, &temp_digits, WHITE);
    let _ = draw_celsius(fb, x_after_digits, y, WHITE);

    let _ = draw_text(fb, cell_to_x(AUX_FAN_LABEL_COL), y, "FAN", CYAN);
    let mut fan_buf: heapless::String<8> = heapless::String::new();
    fmt_fan(fan, &mut fan_buf);
    let _ = draw_value_right(fb, AUX_FAN_VALUE_COL, FAN_VALUE_CELLS, y, &fan_buf, WHITE);
}

pub fn render_dashboard_once<SPI, CS, DC>(
    spi: &mut SPI,
    cs: &mut CS,
    dc: &mut DC,
    model: &DashboardData,
) -> Result<(), SPI::Error>
where
    SPI: SpiBus<u8>,
    CS: OutputPin,
    DC: OutputPin,
{
    clear_framebuffer(BLACK);
    with_framebuffer(|fb| {
        let mut vs: heapless::String<16> = heapless::String::new();
        let mut as_: heapless::String<16> = heapless::String::new();
        let mut ws: heapless::String<16> = heapless::String::new();

        let y0 = MARGIN_TB;
        // Compose top-right battery area (percent or voltage)
        let (soc_text, soc_color) =
            build_soc_text_and_color(model.soc_pct, model.vbat_mv, model.soc_display);
        let soc_w = text_width(&soc_text);
        let soc_x = LOGICAL_WIDTH - MARGIN_LR - soc_w;
        let _ = draw_text(fb, soc_x, y0, &soc_text, soc_color);

        // Draw mode left, clipped to avoid overlap with right area
        let (mode_text, mode_color) = mode_text_and_color(model.mode);
        let max_mode_width = soc_x.saturating_sub(MARGIN_LR);
        let _ = draw_text_clipped(fb, MARGIN_LR, y0, mode_text, mode_color, max_mode_width);

        fmt_voltage(model.in_v_mv, &mut vs);
        fmt_current(model.in_a_ma, &mut as_);
        fmt_power(model.in_w_mw, &mut ws);
        let y1 = MARGIN_TB + LINE_H;
        draw_trio_line(fb, y1, "IN", &vs, &as_, &ws);

        let y2 = MARGIN_TB + 2 * LINE_H;
        match model.mode {
            Mode::Charge => {
                ws.clear();
                fmt_power(model.chg_w_mw, &mut ws);
                draw_trio_line(fb, y2, "CHG", PLACEHOLDER, PLACEHOLDER, &ws);
            }
            Mode::Standby => {
                let mut uptime: heapless::String<16> = heapless::String::new();
                fmt_uptime(model.uptime_secs, &mut uptime);
                draw_trio_line(fb, y2, "RUN ", &uptime, PLACEHOLDER, PLACEHOLDER);
            }
            Mode::Discharge => {
                vs.clear();
                as_.clear();
                ws.clear();
                fmt_voltage(model.out_v_mv, &mut vs);
                fmt_current(model.out_a_ma, &mut as_);
                fmt_power(model.out_w_mw, &mut ws);
                draw_trio_line(fb, y2, "OUT", &vs, &as_, &ws);
            }
        }

        let y3 = MARGIN_TB + 3 * LINE_H;
        draw_aux_line(
            fb,
            y3,
            model.temp_slot,
            model.bat_temp_c,
            model.ups_temp_c,
            model.fan_pct,
        );
    });
    flush_framebuffer(spi, cs, dc)
}
