[[bin]]
name = "smart-battery-driver-stm32g0-demo"
path = "src/main.rs"

[package]
name = "smart-battery-driver-stm32g0-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "0.2.0", path = "../../../../embassy/embassy-stm32", features = [
  "time-driver-any",
  "stm32g031c8",
  "memory-x",
  "unstable-pac",
  "exti",
  "defmt",
] }
embassy-executor = { version = "0.7.0", path = "../../../../embassy/embassy-executor", features = [
  "arch-cortex-m",
  "executor-thread",
  "defmt",
] }
embassy-time = { version = "0.4.0", path = "../../../../embassy/embassy-time", features = ["defmt","defmt-timestamp-uptime","tick-hz-32_768"] }
embassy-embedded-hal = { version = "0.3.0", path = "../../../../embassy/embassy-embedded-hal" }
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features=["print-defmt"] }
embedded-hal = "1.0.0"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
smart-battery-driver = { path = "../..", features=["async","defmt"] }

[profile.dev]
debug = true

[profile.release]
debug = 2
lto = "thin"
opt-level = "z"
panic = "abort"
